version: '3'

services:
  app:
    container_name: server
    restart: always
    build: ./app
    ports:
      - 3000:3000
    depends_on:
      - mongo
    environment:
      - MONGO_USERNAME=${MONGO_ROOT_USER}
      - MONGO_PASSWORD=${MONGO_ROOT_PASSWORD}
      - MONGO_HOSTNAME=mongo
      - MONGO_PORT=27017
      - MONGO_DB=project
    volumes:
      - ./app:/usr/src/app
      # - ./app:/usr/src/app
      # - ./app:/usr/src/app/app
  mongo:
    container_name: mongo
    image: mongo:latest
    restart: always
    env_file:
      - .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
    #   - MONGO_INITDB_DATABASE=project
    volumes:
      - ./data:/data/db
    ports:
      - 27017:27017
  # mongo-express:
  #   image: mongo-express
  #   restart: always
  #   env_file:
  #     - .env
  #   ports:
  #     - '8081:8081'
  #   environment:
  #     - ME_CONFIG_MONGODB_SERVER=mongo
  #     - ME_CONFIG_MONGODB_PORT=27017
  #     - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
  #     - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_ROOT_USER}
  #     - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_ROOT_PASSWORD}
  #     - ME_CONFIG_MONGODB_AUTH_DATABASE=admin
  #     - ME_CONFIG_BASICAUTH_USERNAME=${MONGOEXPRESS_LOGIN}
  #     - ME_CONFIG_BASICAUTH_PASSWORD=${MONGOEXPRESS_PASSWORD}
  #   depends_on:
  #     - mongo
